#--------------------------------------------------------------------------------
# Filename    : gameserver.conf
# Written By  : KIM
#--------------------------------------------------------------------------------

#--------------------------------------------------
# General 
#--------------------------------------------------

#User : KIM
HomePath : ../
TCPPort : 13855 

#내꺼 로그인 서버
LoginServerIP: 127.0.0.1
LoginServerUDPPort : 9909
LoginServerBaseUDPPort : 9909
LoginServerUDPPortNum : 1

GameServerUDPPort : 9997 

#--------------------------------------------------

LoginServerIP2: 127.0.0.1

LoginServerUDPPort2 : 9909
LoginServerBaseUDPPort2 : 5800
LoginServerUDPPortNum2 : 1


#--------------------------------------------------
# Shared - Game Server Section
#--------------------------------------------------
SharedServerIP : 127.0.0.1
SharedServerPort : 9993

#--------------------------------------------------
# BillingSystem Server
#--------------------------------------------------
BillingServerIP : 127.0.0.1
BillingServerPort : 3000

# 애드빌에서 정한 다크에덴 게임 번호
BillingGameNo : 1


#--------------------------------------------------
# china BillingSystem Server
#--------------------------------------------------
#ChinaBillingServerIP : 61.78.53.228
#ChinaBillingServerIP : 127.0.0.1
#ChinaBillingServerPort : 19001

# china billing version number
#ChinaBillingVersionNumber : 1000
# china billing interval (unit:minute). minus point/minute 패킷을 보내는 주기. 분 단뒤
#ChinaBillingMinusInterval : 1

#--------------------------------------------------
# Time. Good~
#--------------------------------------------------
BaseGameTime : 1996-1-1
BaseRealTime : 2000-5-1

#--------------------------------------------------
# DB connection
#--------------------------------------------------
DB_HOST : 127.0.0.1
DB_DB : DARKEDEN
DB_USER : elcastle
DB_PASSWORD : elca005
DB_PORT : 3306

#DIST_DB_HOST : 127.0.0.1
#DIST_DB_DB : DIST_DARKEDEN
#DIST_DB_USER : elcastle
#DIST_DB_PASSWORD : elca005

UI_DB_HOST : 127.0.0.1
UI_DB_DB : DARKEDEN
UI_DB_USER : elcastle
UI_DB_PASSWORD : elca005
UI_DB_PORT : 3306

SMS_DB_HOST : 127.0.0.1
SMS_DB_DB : DARKEDEN
SMS_DB_USER : elcastle
SMS_DB_PASSWORD : elca005
SMS_DB_PORT : 3306

#CBILLING_DB_HOST : 61.78.53.228
#CBILLING_DB_HOST : 127.0.0.1
#CBILLING_DB_DB : test
#CBILLING_DB_USER : elcastle
#CBILLING_DB_PASSWORD : skxmfba
#CBILLING_DB_PORT : 4958
#LoginServerIP: 127.0.0.1
#LoginServerUDPPort : 9996
#GameServerUDPPort : 9997

#MofusServerCode : 0
#MofusIP : 61.78.53.228
#MofusPort : 10001

#--------------------------------------------------
# Time. Good~
#--------------------------------------------------
#BaseGameTime : 1996-1-1
#BaseRealTime : 2000-5-1


#--------------------------------------------------
# LogThread Section 
#--------------------------------------------------

# 로그 서버 주소
LogServerIP : 127.0.0.1

# 로그 서버 포트
LogServerPort : 5000

# 로그 레벨
LogLevel : 2999

#--------------------------------------------------
# item id section
#--------------------------------------------------
Dimension : 0

WorldID : 1

# 서버의 갯수
ServerCount : 1

# 서버마다 틀린 베이스 숫자
ServerID : 0 

# 이 서버에는 종족 전쟁을 하는가?
ActiveRaceWar : 1 

# 이 서버에는 동족(길드) 전쟁을 하는가?
ActiveGuildWar : 1

# 이 서버에는 깃발뺏기를 하는가?
ActiveFlagWar : 1

# 이 서버에는 레벨전쟁 하는가?
ActiveLevelWar : 1

# 이 서버에는 종족 전쟁 신청을 받는가?
JoinRaceWar : 1

# 넷마블용
IsNetMarble : 0

# 넷마블용
IsJumping : 0

# 머리 갯수 셀까 말까
HeadCount : 0

# 하드코어
Hardcore : 0
