#
#
# Filename    : sharedserver.conf
# Written By  : KIM
#
#--------------------------------------------------------------------------------

#--------------------------------------------------------------------------------
# User Section
#--------------------------------------------------------------------------------

User : KIM
HomePath : /home/darkeden/vs/bin

#--------------------------------------------------------------------------------
# Game - Shared Server Section
#--------------------------------------------------------------------------------
TCPPort : 9993

#--------------------------------------------------
# DB connection
#--------------------------------------------------
DB_HOST : 192.168.147.128
DB_DB : DARKEDEN
DB_USER : elcastle
DB_PASSWORD : elca005
DB_PORT : 3306

UI_DB_HOST : 192.168.147.128
UI_DB_DB : DARKEDEN
UI_DB_USER : elcastle
UI_DB_PASSWORD : elca005
UI_DB_PORT : 3306

DIST_DB_HOST : 192.168.147.128
DIST_DB_DB : DARKEDEN
DIST_DB_USER : elcastle
DIST_DB_PASSWORD : elca005
DIST_DB_PORT : 3306

#--------------------------------------------------------------------------------
# LogThread Section 
#--------------------------------------------------------------------------------

# 로그 서버 주소
LogServerIP : 192.168.147.128

# 로그 서버 포트
LogServerPort : 5001

# 로그 레벨
LogLevel : 2999


#--------------------------------------------------
# World Info
#--------------------------------------------------
Dimension : 3

WorldID : 1
#WorldID : 3

